$ErrorActionPreference = "Stop"

  <#
  OpenRelay Local Safe — tool onboarding script generator.

  Writes project-internal helper scripts that local AI tools (Codex,
  OpenClaw, OpenCode, Aider, Goose, Continue, Claude Code, Amp) can source
  to point at the running relay. The scripts only set environment variables
  for the current shell process. They do NOT touch global system env
  variables, the Windows Registry, or any token / cookie / session
  storage.

  Generated files (live next to this script, i.e. in the project root):
    tool-env.ps1      - dot-source from Windows PowerShell
    tool-env.cmd      - call from Windows CMD
    tool-env.sh       - source from WSL / Linux / macOS Bash
    tool-verify.ps1   - run a smoke /v1/models + /v1/chat/completions check
    tool-verify.cmd   - same for CMD
    tool-verify.sh    - same for WSL / Linux / macOS Bash

  Usage (from the project root, in Windows PowerShell):

      powershell -ExecutionPolicy Bypass -File scripts\write-tool-env.ps1
      . .\tool-env.ps1
      .\tool-verify.ps1
#>

$root = Split-Path -Parent $PSScriptRoot
$psOutput = Join-Path $root "tool-env.ps1"
$cmdOutput = Join-Path $root "tool-env.cmd"
$shOutput = Join-Path $root "tool-env.sh"
$verifyPsOutput = Join-Path $root "tool-verify.ps1"
$verifyCmdOutput = Join-Path $root "tool-verify.cmd"
$verifyShOutput = Join-Path $root "tool-verify.sh"
$port = if ($env:PORT) { $env:PORT } else { "18765" }
$baseUrl = "http://127.0.0.1:$port/v1"
$apiKey = if ($env:RELAY_TOKEN) { $env:RELAY_TOKEN } else { "local" }

# Shared env-var block covering all 7 supported tools. Tools that do
# not understand a given var just ignore it; sourcing the script in a
# shell where the tool is launched is enough.
$envVars = @(
  "OPENAI_BASE_URL",
  "OPENAI_API_BASE",
  "OPENAI_API_KEY",
  "ANTHROPIC_BASE_URL",
  "ANTHROPIC_API_KEY"
)

# .ps1 — PowerShell
$psBody = New-Object System.Text.StringBuilder
[void]$psBody.AppendLine("# Generated by RelayForge.")
[void]$psBody.AppendLine("# Run in the SAME PowerShell window that will start the tool:")
[void]$psBody.AppendLine("#   . .\tool-env.ps1")
[void]$psBody.AppendLine("# This only sets process-local env vars; it does NOT modify")
[void]$psBody.AppendLine("# system / user environment or any tool config file.")
foreach ($name in $envVars) {
  $value = if ($name -in @("OPENAI_BASE_URL", "OPENAI_API_BASE", "ANTHROPIC_BASE_URL")) { $baseUrl } else { $apiKey }
  [void]$psBody.AppendLine("`$env:$name = `"$value`"")
}
[void]$psBody.AppendLine("")
[void]$psBody.AppendLine("# Per-tool aliases the tools look at:")
[void]$psBody.AppendLine("`$env:CODEX_BASE_URL = `"$baseUrl`"")
[void]$psBody.AppendLine("`$env:CODEX_API_KEY = `"$apiKey`"")
[void]$psBody.AppendLine("`$env:OPENCLAW_BASE_URL = `"$baseUrl`"")
[void]$psBody.AppendLine("`$env:OPENCLAW_API_KEY = `"$apiKey`"")
[void]$psBody.AppendLine("`$env:OPENCODE_BASE_URL = `"$baseUrl`"")
[void]$psBody.AppendLine("`$env:OPENCODE_API_KEY = `"$apiKey`"")
[void]$psBody.AppendLine("`$env:AIDER_OPENAI_API_BASE = `"$baseUrl`"")
[void]$psBody.AppendLine("`$env:AIDER_OPENAI_API_KEY = `"$apiKey`"")
[void]$psBody.AppendLine("`$env:GOOSE_OPENAI_BASE_URL = `"$baseUrl`"")
[void]$psBody.AppendLine("`$env:GOOSE_OPENAI_API_KEY = `"$apiKey`"")
[void]$psBody.AppendLine("`$env:CONTINUE_OPENAI_BASE_URL = `"$baseUrl`"")
[void]$psBody.AppendLine("`$env:CONTINUE_OPENAI_API_KEY = `"$apiKey`"")
[void]$psBody.AppendLine("`$env:AMP_BASE_URL = `"$baseUrl`"")
[void]$psBody.AppendLine("`$env:AMP_API_KEY = `"$apiKey`"")
[System.IO.File]::WriteAllText($psOutput, $psBody.ToString(), [System.Text.Encoding]::UTF8)

# .cmd — Windows CMD
$cmdBody = New-Object System.Text.StringBuilder
[void]$cmdBody.AppendLine("@echo off")
[void]$cmdBody.AppendLine("rem Generated by RelayForge.")
[void]$cmdBody.AppendLine("rem Run in the SAME CMD window that will start the tool:")
[void]$cmdBody.AppendLine("rem   call .\tool-env.cmd")
[void]$cmdBody.AppendLine("rem This only sets process-local env vars; it does NOT modify")
[void]$cmdBody.AppendLine("rem system / user environment or any tool config file.")
foreach ($name in $envVars) {
  $value = if ($name -in @("OPENAI_BASE_URL", "OPENAI_API_BASE", "ANTHROPIC_BASE_URL")) { $baseUrl } else { $apiKey }
  [void]$cmdBody.AppendLine("set $name=$value")
}
[void]$cmdBody.AppendLine("")
[void]$cmdBody.AppendLine("rem Per-tool aliases the tools look at:")
[void]$cmdBody.AppendLine("set CODEX_BASE_URL=$baseUrl")
[void]$cmdBody.AppendLine("set CODEX_API_KEY=$apiKey")
[void]$cmdBody.AppendLine("set OPENCLAW_BASE_URL=$baseUrl")
[void]$cmdBody.AppendLine("set OPENCLAW_API_KEY=$apiKey")
[void]$cmdBody.AppendLine("set OPENCODE_BASE_URL=$baseUrl")
[void]$cmdBody.AppendLine("set OPENCODE_API_KEY=$apiKey")
[void]$cmdBody.AppendLine("set AIDER_OPENAI_API_BASE=$baseUrl")
[void]$cmdBody.AppendLine("set AIDER_OPENAI_API_KEY=$apiKey")
[void]$cmdBody.AppendLine("set GOOSE_OPENAI_BASE_URL=$baseUrl")
[void]$cmdBody.AppendLine("set GOOSE_OPENAI_API_KEY=$apiKey")
[void]$cmdBody.AppendLine("set CONTINUE_OPENAI_BASE_URL=$baseUrl")
[void]$cmdBody.AppendLine("set CONTINUE_OPENAI_API_KEY=$apiKey")
[void]$cmdBody.AppendLine("set AMP_BASE_URL=$baseUrl")
[void]$cmdBody.AppendLine("set AMP_API_KEY=$apiKey")
[System.IO.File]::WriteAllText($cmdOutput, $cmdBody.ToString(), [System.Text.Encoding]::UTF8)

# .sh — WSL / Linux / macOS Bash
$shBody = New-Object System.Text.StringBuilder
[void]$shBody.AppendLine("# Generated by RelayForge.")
[void]$shBody.AppendLine("# Run in the SAME shell that will start the tool:")
[void]$shBody.AppendLine("#   source ./tool-env.sh")
[void]$shBody.AppendLine("# This only exports process-local env vars; it does NOT modify")
[void]$shBody.AppendLine("# system / user environment or any tool config file.")
foreach ($name in $envVars) {
  $value = if ($name -in @("OPENAI_BASE_URL", "OPENAI_API_BASE", "ANTHROPIC_BASE_URL")) { $baseUrl } else { $apiKey }
  [void]$shBody.AppendLine("export $name=`"$value`"")
}
[void]$shBody.AppendLine("")
[void]$shBody.AppendLine("# Per-tool aliases the tools look at:")
[void]$shBody.AppendLine("export CODEX_BASE_URL=`"$baseUrl`"")
[void]$shBody.AppendLine("export CODEX_API_KEY=`"$apiKey`"")
[void]$shBody.AppendLine("export OPENCLAW_BASE_URL=`"$baseUrl`"")
[void]$shBody.AppendLine("export OPENCLAW_API_KEY=`"$apiKey`"")
[void]$shBody.AppendLine("export OPENCODE_BASE_URL=`"$baseUrl`"")
[void]$shBody.AppendLine("export OPENCODE_API_KEY=`"$apiKey`"")
[void]$shBody.AppendLine("export AIDER_OPENAI_API_BASE=`"$baseUrl`"")
[void]$shBody.AppendLine("export AIDER_OPENAI_API_KEY=`"$apiKey`"")
[void]$shBody.AppendLine("export GOOSE_OPENAI_BASE_URL=`"$baseUrl`"")
[void]$shBody.AppendLine("export GOOSE_OPENAI_API_KEY=`"$apiKey`"")
[void]$shBody.AppendLine("export CONTINUE_OPENAI_BASE_URL=`"$baseUrl`"")
[void]$shBody.AppendLine("export CONTINUE_OPENAI_API_KEY=`"$apiKey`"")
[void]$shBody.AppendLine("export AMP_BASE_URL=`"$baseUrl`"")
[void]$shBody.AppendLine("export AMP_API_KEY=`"$apiKey`"")
[System.IO.File]::WriteAllText($shOutput, $shBody.ToString(), [System.Text.Encoding]::UTF8)

# tool-verify.ps1 — PowerShell smoke check
$verifyPsBody = @'
$ErrorActionPreference = "Stop"
$baseUrl = "__BASE_URL__"
$apiKey = "__API_KEY__"
Write-Host "[tool-verify] GET $baseUrl/v1/models"
try {
  $models = Invoke-RestMethod -Uri "$baseUrl/v1/models" -Headers @{ Authorization = "Bearer $apiKey" } -TimeoutSec 5
  Write-Host ("[tool-verify] /v1/models ok: " + $models.data.Count + " models")
} catch {
  Write-Host "[tool-verify] /v1/models failed: $_" -ForegroundColor Red
  Write-Host "[tool-verify] Is the relay running? Try: npm.cmd run start" -ForegroundColor Yellow
  exit 1
}
Write-Host "[tool-verify] POST $baseUrl/v1/chat/completions (model = auto)"
$body = @{ model = "auto"; messages = @(@{ role = "user"; content = "reply with the single word: pong" }) } | ConvertTo-Json -Depth 10 -Compress
try {
  $chat = Invoke-RestMethod -Uri "$baseUrl/v1/chat/completions" -Method Post -ContentType "application/json" -Headers @{ Authorization = "Bearer $apiKey" } -Body $body -TimeoutSec 30
  Write-Host "[tool-verify] /v1/chat/completions ok: model=$($chat.model)"
} catch {
  Write-Host "[tool-verify] /v1/chat/completions failed: $_" -ForegroundColor Red
  exit 2
}
Write-Host "[tool-verify] OK — Codex, OpenClaw, OpenCode, Aider, Goose, Continue, Claude Code, Amp should all be able to talk to the relay through $baseUrl."
'@
$verifyPsBody = $verifyPsBody.Replace("__BASE_URL__", $baseUrl).Replace("__API_KEY__", $apiKey)
[System.IO.File]::WriteAllText($verifyPsOutput, $verifyPsBody.ToString(), [System.Text.Encoding]::UTF8)

# tool-verify.cmd — Windows CMD smoke check
$verifyCmdBody = @'
@echo off
setlocal
set BASE_URL=__BASE_URL__
set API_KEY=__API_KEY__
echo [tool-verify] GET %BASE_URL%/v1/models
curl.exe -sS -H "Authorization: Bearer %API_KEY%" "%BASE_URL%/v1/models" -o "%TEMP%\openrelay-models.json" -w "HTTP %%{http_code}%%"
if errorlevel 1 (
  echo [tool-verify] /v1/models failed. Is the relay running? Try: npm.cmd run start
  exit /b 1
)
echo [tool-verify] /v1/models ok
echo [tool-verify] POST %BASE_URL%/v1/chat/completions (model = auto)
curl.exe -sS -X POST -H "Authorization: Bearer %API_KEY%" -H "Content-Type: application/json" -d "{\"model\":\"auto\",\"messages\":[{\"role\":\"user\",\"content\":\"reply with the single word: pong\"}]}" "%BASE_URL%/v1/chat/completions" -o "%TEMP%\openrelay-chat.json" -w "HTTP %%{http_code}%%"
if errorlevel 1 (
  echo [tool-verify] /v1/chat/completions failed.
  exit /b 2
)
echo [tool-verify] /v1/chat/completions ok
echo [tool-verify] OK — Codex, OpenClaw, OpenCode, Aider, Goose, Continue, Claude Code, Amp should all be able to talk to the relay through %BASE_URL%.
'@
$verifyCmdBody = $verifyCmdBody.Replace("__BASE_URL__", $baseUrl).Replace("__API_KEY__", $apiKey)
[System.IO.File]::WriteAllText($verifyCmdOutput, $verifyCmdBody, [System.Text.Encoding]::UTF8)

# tool-verify.sh — Bash smoke check. Use a single-quoted here-string
# to avoid PowerShell interpolating the $(...) Bash subshells.
$verifyShBody = @'
#!/usr/bin/env bash
set -e
BASE_URL="__BASE_URL__"
API_KEY="__API_KEY__"
echo "[tool-verify] GET $BASE_URL/v1/models"
models_status=$(curl -sS -H "Authorization: Bearer $API_KEY" -o /tmp/openrelay-models.json -w "%{http_code}" "$BASE_URL/v1/models" || true)
if [ "$models_status" != "200" ]; then
  echo "[tool-verify] /v1/models failed (HTTP $models_status). Is the relay running? Try: npm.cmd run start" >&2
  exit 1
fi
echo "[tool-verify] /v1/models ok"
echo "[tool-verify] POST $BASE_URL/v1/chat/completions (model = auto)"
chat_status=$(curl -sS -X POST -H "Authorization: Bearer $API_KEY" -H "Content-Type: application/json" \
  -d '{"model":"auto","messages":[{"role":"user","content":"reply with the single word: pong"}]}' \
  -o /tmp/openrelay-chat.json -w "%{http_code}" "$BASE_URL/v1/chat/completions" || true)
if [ "$chat_status" != "200" ]; then
  echo "[tool-verify] /v1/chat/completions failed (HTTP $chat_status)" >&2
  exit 2
fi
echo "[tool-verify] /v1/chat/completions ok"
echo "[tool-verify] OK — Codex, OpenClaw, OpenCode, Aider, Goose, Continue, Claude Code, Amp should all be able to talk to the relay through $BASE_URL."
'@
$verifyShBody = $verifyShBody.Replace("__BASE_URL__", $baseUrl).Replace("__API_KEY__", $apiKey)
[System.IO.File]::WriteAllText($verifyShOutput, $verifyShBody, [System.Text.Encoding]::UTF8)

Write-Host "Wrote:"
Write-Host "  $psOutput"
Write-Host "  $cmdOutput"
Write-Host "  $shOutput"
Write-Host "  $verifyPsOutput"
Write-Host "  $verifyCmdOutput"
Write-Host "  $verifyShOutput"
Write-Host ""
Write-Host "PowerShell: . \`"$psOutput\`"; \`"$verifyPsOutput\`""
Write-Host "CMD:        call \`"$cmdOutput\`"; \`"$verifyCmdOutput\`""
Write-Host "Bash/WSL:   source \`"$shOutput\`"; bash \`"$verifyShOutput\`""
